name: Nuget

on:
  push:
    branches: [ master ]
    
jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup dotnet SDK 3.1
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.201
    - name: test with dotnet
      run: dotnet test
    - name: pack
      run: dotnet pack --configuration Release src/KubernetesClient -o pkg
    - name: push
      run: dotnet nuget push pkg\*.nupkg -s https://www.nuget.org/ -k ${{ secrets.nuget_api_key }} 
