name: Nuget

on:
  push:
    branches: [ master ]
    
jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 0
    - name: Setup dotnet runtime 2.0.9
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.1.202
    - name: Setup dotnet runtime 2.1.17
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.1.805
    - name: Setup dotnet SDK 3.1
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.201
    - name: Setup SxS dotnet
      if: matrix.os == 'windows-latest'
      run: |
        (robocopy %DOTNET_ROOT:3.1.201=2.1.805% %DOTNET_ROOT% /E /XC /XN /XO /NFL /NDL /NJH /NJS /NP) ^& if %ERRORLEVEL% geq 8 exit /B %ERRORLEVEL%
        (robocopy %DOTNET_ROOT:3.1.201=2.1.202% %DOTNET_ROOT% /E /XC /XN /XO /NFL /NDL /NJH /NJS /NP) ^& if %ERRORLEVEL% geq 8 exit /B %ERRORLEVEL%
        exit /B 0
      shell: cmd
    - name: Test
      run: dotnet test
    - name: Pack
      run: dotnet pack --configuration Release src/KubernetesClient -o pkg
    - name: Push
      run: dotnet nuget push pkg\*.nupkg -s https://www.nuget.org/ -k ${{ secrets.nuget_api_key }}
